In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np
from sklearn.linear_model import LinearRegression

C:\Users\syedf\AppData\Local\Temp/ipykernel_24196/448944745.py:4: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport


In [2]:
df = pd.read_csv('C:/Users/syedf/Full stack data science/Machine Learning/archive (1)/Advertising.csv')

In [3]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [4]:
data_x = df[['TV','Radio','Newspaper']]
data_x

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [5]:
y = df.Sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [6]:
from sklearn.linear_model import LinearRegression


In [7]:
dm = LinearRegression()
dm.fit(data_x,y)

LinearRegression()

In [8]:
dm.intercept_

2.9388893694594085

In [9]:
dm.coef_
# y = mx + c
# y = 0.045TV + 0.188Radio + -0.001Newspaper + 2.938

array([ 0.04576465,  0.18853002, -0.00103749])

In [10]:
dm.score(data_x,y)
# when there are 3 data will given

0.8972106381789522

In [11]:
data_y = df[['TV','Radio']]
data_y

TV  Radio
0    230.1   37.8
1     44.5   39.3
2     17.2   45.9
3    151.5   41.3
4    180.8   10.8
..     ...    ...
195   38.2    3.7
196   94.2    4.9
197  177.0    9.3
198  283.6   42.0
199  232.1    8.6

[200 rows x 2 columns]

In [12]:
data_z = df[['Newspaper']]
data_z

Newspaper
0         69.2
1         45.1
2         69.3
3         58.5
4         58.4
..         ...
195       13.8
196        8.1
197        6.4
198       66.2
199        8.7

[200 rows x 1 columns]

In [13]:
data_v = df[['Radio']]
data_v

Radio
0     37.8
1     39.3
2     45.9
3     41.3
4     10.8
..     ...
195    3.7
196    4.9
197    9.3
198   42.0
199    8.6

[200 rows x 1 columns]

In [14]:
dm1 = LinearRegression()
dm1.fit(data_y,y)

LinearRegression()

In [15]:
dm1.intercept_

2.9210999124051362

In [16]:
dm1.coef_

array([0.04575482, 0.18799423])

In [17]:
dm1.score(data_y,y)
# when there are 2 (TV and Radio) data will given

0.8971942610828956

In [18]:
dm2 = LinearRegression()
dm2.fit(data_z,y)

LinearRegression()

In [19]:
dm2.intercept_

12.35140706927816

In [20]:
dm2.coef_

array([0.0546931])

In [21]:
dm2.score(data_z,y)
# when there are 1(only Newspaper) data will given

0.05212044544430516

In [22]:
dm3 = LinearRegression()
dm3.fit(data_v,y)

LinearRegression()

In [23]:
dm3.intercept_

9.311638095158283

In [24]:
dm3.coef_

array([0.20249578])

In [25]:
dm3.score(data_v,y)
# when there are 1(only radio) data will given

0.33203245544529525

In [26]:
import statsmodels.formula.api as smf

In [27]:
# OLS = Ordinary Least Square model
dm = smf.ols(formula = 'Sales ~ TV',data = df).fit()
dm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Wed, 04 Oct 2023   Prob (F-statistic):           1.47e-42
Time:                        17:58:55   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
dma = smf.ols(formula = 'Sales ~ TV+Radio',data = df).fit()
dma.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     859.6
Date:                Wed, 04 Oct 2023   Prob (F-statistic):           4.83e-98
Time:                        17:58:55   Log-Likelihood:                -386.20
No. Observations:                 200   AIC:                             778.4
Df Residuals:                     197   BIC:                             788.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9211      0.294      9.919      0.000       2.340       3.502
TV             0.0458      0.001     32.909      0.000       0.043       0.048
Radio          0.1880      0.008     23.382      0.000       0.172       0.204
==============================================================================
Omnibus:                       60.022   Durbin-Watson:                   2.081
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              148.679
Skew:                          -1.323   Prob(JB):                     5.19e-33
Kurtosis:                       6.292   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [29]:
dmb = smf.ols(formula = 'Sales ~ TV+Radio+Newspaper',data = df).fit()
dmb.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Wed, 04 Oct 2023   Prob (F-statistic):           1.58e-96
Time:                        17:58:55   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
Radio          0.1885      0.009     21.893      0.000       0.172       0.206
Newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# VIF = Varience Inflation Factor
# VIF = (1/(1-R^2)), R^2 = Residuals it tells you that how close your line is wrt data points
# if VIF > 10 in that case you are suppose to consider your dataset is highly colinear
   


# Regularization:-

Q1. Why regularization is imp.?

If i could get more control on error term then it could be more generilized model

This is regulaziration

# LASSO or L1 or 1st  Technique of Regularization
Least Absolute Sinkage and Selection Operator 

It is the one of the Regularization technique

# RIDGE REGRESSION or L2 or 2nd Technique of Regularization

# ELASTIC NET or 3rd Technique of Regularization

# Q2.how did you build a robust model
Ans: By using regularization

In [30]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
df1 = pd.read_csv('C:/Users/syedf/Downloads/archive (1)/Admission_Predict.csv')

In [32]:
df1

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [33]:
df2 = pd.read_csv('C:/Users/syedf/Downloads/archive (1)/Admission_Predict_Ver1.1.csv')

In [34]:
df2

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]